# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(4, 0))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.videoLabel.setObjectName("videoLabel")

        self.Jarvislabel = QtWidgets.QLabel(self.centralwidget)
        self.Jarvislabel.setGeometry(QtCore.QRect(640, 80, 441, 311))
        self.Jarvislabel.setText("")
        self.Jarvislabel.setPixmap(QtGui.QPixmap("../../../../Advanced_Jarvis/GUI/Jarvis_Gui (1).gif"))
        self.Jarvislabel.setScaledContents(True)
        self.Jarvislabel.setObjectName("Jarvislabel")

        self.Earth = QtWidgets.QLabel(self.centralwidget)
        self.Earth.setGeometry(QtCore.QRect(-30, 480, 371, 201))
        self.Earth.setText("")
        self.Earth.setPixmap(QtGui.QPixmap("../../../../Advanced_Jarvis/GUI/Earth.gif"))
        self.Earth.setScaledContents(False)
        self.Earth.setObjectName("Earth")

        self.textBox1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBox1.setGeometry(QtCore.QRect(640, 0, 431, 71))
        font = QtGui.QFont()
        font.setFamily("TESLA")
        self.textBox1.setFont(font)
        self.textBox1.setReadOnly(True)
        self.textBox1.setObjectName("textBox1")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoLabel.setText(_translate("MainWindow", "TextLabel"))
        self.textBox1.setMarkdown(_translate("MainWindow", "# FACE RECOGNITION BY JARVIS\n"
                                                           "\n"
                                                           ""))
        self.textBox1.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "hr { height: 1px; border-width: 0; }\n"
                                         "li.unchecked::marker { content: \"\\2610\"; }\n"
                                         "li.checked::marker { content: \"\\2612\"; }\n"
                                         "</style></head><body style=\" font-family:\'TESLA\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<h1 align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:16pt; font-weight:700; font-style:italic; color:#ffffff;\">FACE RECOGNITION BY JARVIS</span></h1></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
