# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(1080, 725)
        loginWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kartisTechLabel = QtWidgets.QLabel(self.centralwidget)
        self.kartisTechLabel.setGeometry(QtCore.QRect(220, 0, 640, 81))
        self.kartisTechLabel.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "border-color: rgb(255, 255, 255);")
        self.kartisTechLabel.setText("")
        self.kartisTechLabel.setPixmap(QtGui.QPixmap("../../../gui_tools/KartisTechnology(white).png"))
        self.kartisTechLabel.setScaledContents(True)
        self.kartisTechLabel.setObjectName("kartisTechLabel")
        self.loginmainFrame = QtWidgets.QFrame(self.centralwidget)
        self.loginmainFrame.setGeometry(QtCore.QRect(220, 75, 640, 641))
        self.loginmainFrame.setAutoFillBackground(False)
        self.loginmainFrame.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                          "border-style: solid;\n"
                                          "border-width: 5px 5px 5px 5px;\n"
                                          "border-radius: 30px;")
        self.loginmainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginmainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginmainFrame.setObjectName("loginmainFrame")
        self.LoginButton = QtWidgets.QPushButton(self.loginmainFrame)
        self.LoginButton.setGeometry(QtCore.QRect(183, 340, 274, 101))
        self.LoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginButton.setStyleSheet(
            "border-image: url(E:/CODING/Artificial_Intelligence/FacialRecogByJARVIS/with GUI/gui_tools/login.png);\n"
            "")
        self.LoginButton.setText("")
        self.LoginButton.setFlat(False)
        self.LoginButton.setObjectName("LoginButton")
        self.passwordEdit = QtWidgets.QLineEdit(self.loginmainFrame)
        self.passwordEdit.setGeometry(QtCore.QRect(125, 250, 391, 71))
        self.passwordEdit.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                        "font: 30pt \"IRON MAN OF WAR 2 NCV\";\n"
                                        "border-style: solid;\n"
                                        "border-width: 1px 1px 1px 1px;\n"
                                        "border-radius: 20px;\n"
                                        "color:rgb(255, 255, 255)")
        self.passwordEdit.setObjectName("passwordEdit")
        self.usernameEdit = QtWidgets.QLineEdit(self.loginmainFrame)
        self.usernameEdit.setGeometry(QtCore.QRect(125, 150, 391, 71))
        self.usernameEdit.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                        "font: 30pt \"IRON MAN OF WAR 2 NCV\";\n"
                                        "border-style: solid;\n"
                                        "border-width: 1px 1px 1px 1px;\n"
                                        "border-radius: 20px;\n"
                                        "color:rgb(255, 255, 255)")
        self.usernameEdit.setObjectName("usernameEdit")
        self.LoginButton_2 = QtWidgets.QPushButton(self.loginmainFrame)
        self.LoginButton_2.setGeometry(QtCore.QRect(430, 522, 201, 91))
        self.LoginButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginButton_2.setStyleSheet(
            "border-image: url(E:/CODING/Artificial_Intelligence/FacialRecogByJARVIS/with GUI/gui_tools/exit.png);\n"
            "")
        self.LoginButton_2.setText("")
        self.LoginButton_2.setFlat(False)
        self.LoginButton_2.setObjectName("LoginButton_2")
        self.LoginButton_3 = QtWidgets.QPushButton(self.loginmainFrame)
        self.LoginButton_3.setGeometry(QtCore.QRect(230, 517, 201, 91))
        self.LoginButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginButton_3.setStyleSheet(
            "border-image: url(E:/CODING/Artificial_Intelligence/FacialRecogByJARVIS/with GUI/gui_tools/back.png);\n"
            "")
        self.LoginButton_3.setText("")
        self.LoginButton_3.setFlat(False)
        self.LoginButton_3.setObjectName("LoginButton_3")
        self.retryButton = QtWidgets.QPushButton(self.loginmainFrame)
        self.retryButton.setGeometry(QtCore.QRect(30, 525, 200, 81))
        self.retryButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.retryButton.setStyleSheet(
            "border-image: url(E:/CODING/Artificial_Intelligence/FacialRecogByJARVIS/with GUI/gui_tools/retry.png);\n"
            "")
        self.retryButton.setText("")
        self.retryButton.setFlat(False)
        self.retryButton.setObjectName("retryButton")






        self.illegalentrylabel = QtWidgets.QLabel(self.loginmainFrame)
        self.illegalentrylabel.setEnabled(True)
        self.illegalentrylabel.setGeometry(QtCore.QRect(100, 90, 441, 351))
        self.illegalentrylabel.setStyleSheet("border:none;")
        self.illegalentrylabel.setText("")
        self.illegalentrylabel.setPixmap(QtGui.QPixmap("E:/CODING/Artificial_Intelligence/FacialRecogByJARVIS/with GUI/gui_tools/illegalEntry.gif"))
        self.illegalentrylabel.setScaledContents(True)
        self.illegalentrylabel.setObjectName("illegalentrylabel")
        self.illegalentrylabel.hide()








        loginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Login"))
        self.passwordEdit.setPlaceholderText(_translate("loginWindow", "Password"))
        self.usernameEdit.setPlaceholderText(_translate("loginWindow", "Username"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QMainWindow()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec_())
